### ISSUE TITLE
error when loading popp.gpkg

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgpkg#1]
when loading popp.gpkg the layer displays, but i get the error:Traceback (most recent call last):
  File "C:/Users/bakkea/.qgis2/python/plugins\QgisGeopackage\qgis_geopackage.py", line 125, in read
    project_path = gpkg.read(gpkg_path)
  File "C:/Users/bakkea/.qgis2/python/plugins\QgisGeopackage\qgpkg.py", line 461, in read
    self.loadContext(context[0],dictLayers)
  File "C:/Users/bakkea/.qgis2/python/plugins\QgisGeopackage\qgpkg.py", line 306, in loadContext
    layer.setShortName(key)
AttributeError: 'QgsVectorLayer' object has no attribute 'setShortName'

**Comment by doublebyte1** [comment]
Which version of QGIS are you using? This sounds like a functionality broken in the API

**Comment by pvgenuchten** [comment]
qgis 2.10
does it make sense to try-catch as many as possible of these errors and in the catch use default values?

**Comment by doublebyte1** [comment]
I cannot reproduce this error. The function `setShortName` is part of the QgsMapLayer class, on QGIS core:

https://github.com/qgis/QGIS/blob/master/src/core/qgsmaplayer.h

For some reason, this does not seem to be available on your QGIS version (maybe in this version there is no Python binding for this method?) 2.10 is still a bit outdated. Try to update at least to the latest release (
2.18.3.)

**Comment by doublebyte1** [comment]
> does it make sense to try-catch as many as possible of these errors and in the catch use default values?

In this case a default value would not solve anything. QGIS is just not finding this method, so it is not able to set the short name of the layer.
