### ISSUE TITLE
layers are not loaded with SLD style from geopackage

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgpkg#2]
loading multiple_layers.gpkg works, but it seems not be using the sld to create the layer, that example has an SLD with red dots, but on the map it uses a random color

**Comment by doublebyte1** [comment]
I cannot reproduce this on my computer (see screenshot bellow). Can you have a look at the error log on the python console, to see if something comes up? 

![screenshot](https://cloud.githubusercontent.com/assets/1038897/22598132/bcfb41c4-ea32-11e6-9d58-aec1adf07d8a.png)

**Comment by pvgenuchten** [comment]
ah, looks good, for me (qgis 2.10) there are green dots and purple polygons, let me upgrade my qgis
