### ISSUE TITLE
do we need an intermediate screen to select layers to load?

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgpkg#3]
when loading the gpkg (and it contains multiple tables) an intermediate screen is shown to select layers to load, do we need that screen?
i think no, all layers that are mentioned in the ows-context should be loaded, their activated status should be taken from the ows-context
i guess the idea of that screen is to prevent a lot of layers are loaded instantly, a better way is to add them to the toc, but not activate them by default, but in the ows approach this is actually managed by the ows-context

**Comment by doublebyte1** [comment]
Unfortunately we cannot change that behavior through the QGIS python API :-( QGIS will always display this dialog when attempting to load multiple layers from a gpkg, using` iface.addVectorLayer` and the `OGR` driver.

**Comment by pvgenuchten** [comment]
oops

**Comment by pvgenuchten** [comment]
resolved by https://github.com/GeoCat/qgpkg/commit/8b2a39866313012f146cf161712020337e9af0dd
