### ISSUE TITLE
unwanted geopackage tables are shown in "add layers" panel

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgpkg#5]
in qgis 18, when importing a geopackage, then in intermediate layer-selection panel all geopackage tables are shown (also the extension tables)

**Comment by doublebyte1** [comment]
I am not sure I understand the issue. When you load the multiple_layers.gpkg, any other tables are shown apart from the ones you see on the picture?

![load_gpkg](https://cloud.githubusercontent.com/assets/1038897/23794897/fc047176-0592-11e7-9ef6-1f18b9fd32ee.png)

**Comment by doublebyte1** [comment]
> in qgis 18

 Please have in mind that this version is quite old. The current release is on 2.18.3, and we are working on 2.99-master, with the aim of supporting the plugin on QGIS3

**Comment by pvgenuchten** [comment]
ok, i'll check, i use qgis on mac, so am a bit stuck with the kyngchaos builds, now 2.18.2

**Comment by doublebyte1** [comment]
2.18 should be fine. Does the error reproduce on this version, using our latest code?

**Comment by pvgenuchten** [comment]
resolved by https://github.com/GeoCat/qgpkg/commit/8b2a39866313012f146cf161712020337e9af0dd
