### ISSUE TITLE
sld error

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgpkg#6]
in qgis 2.18.2 on mac

this is probably a qgis bug, so probably not relevant here

in the example geopackage a third pink style is applied to all features of layer grassland which should actually be applied to none, because its filter is

```
<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:PropertyIsEqualTo>
              <ogc:PropertyName>F_CODE< /ogc:PropertyName>
              <ogc:Literal></ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
```

**Comment by doublebyte1** [comment]
This is a problem in the QGIS SLD support, which is outside the scope of this plugin.
We load the style with this call, and we have no control on how its actually loaded:
`layer.loadSldStyle`
