### ISSUE TITLE
context layers seem not used when loading geopackage

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgpkg#7]
when multiple layers in ows-context reference a single table, only a single instance of that layer is loaded

**Comment by doublebyte1** [comment]
Could you provide a sample file with this example?

**Comment by doublebyte1** [comment]
The plugin works fine with a gpkg in this format : https://github.com/GeoCat/qgpkg/blob/ows-spec/examples/multiple_layers.gpkg

**Comment by pvgenuchten** [comment]
resolved by https://github.com/GeoCat/qgpkg/commit/8b2a39866313012f146cf161712020337e9af0dd
