### ISSUE TITLE
layers are prefixed with 'multiple_layers'

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgpkg#8]
in the table-of-contents all layers are prefixed with 'multiple_layers', is this related to the python-api to load layers? is there a way to remove it (tested on qgis 2.18.2)

**Comment by doublebyte1** [comment]
Yes, this is how the API works. If you load one layer from the geopackage, you are able to set the name of that layer programatically:
`iface.addVectorLayer("/home/joana/git/qgpkg/examples/popp.gpkg", "test", "ogr")`
(the layer would be called "test", or if you leave the layer_name empty, it would default to the geopackage name: "popp")
On the other hand, if you load multiple layers from the geopackage, QGIS will just ignore the layer name option:
`iface.addVectorLayer("/home/joana/git/qgpkg/examples/multiple_layers.gpkg", "test", "ogr")`
In this case, it will name each layer after the table name, prefixed by the geopackage name.
I did not check in detail how layers are loaded in QGIS core, but I suspect it is using the GDAL/OGR library.
